### ISSUE TITLE
请问如何导出的呢

### ISSUE THREAD

**Issue by komomon** [izj007/wechat#2]
请问如何导出的呢

**Comment by izj007** [comment]
搞了个微信机器人，把每天看过的或准备看的分享给机器人就存到这里了

**Comment by komomon** [comment]
> 搞了个微信机器人，把每天看过的或准备看的分享给机器人就存到这里了

能否把传到git的代码共享一下呀，大佬或者传到你的github  我去star

**Comment by komomon** [comment]
> 搞了个微信机器人，把每天看过的或准备看的分享给机器人就存到这里了
 
 能否把文章传到github上的代码共享一下呀，大佬或者传到你的github 我去star

**Comment by izj007** [comment]
代码太烂了……
