### ISSUE TITLE
求问怎么做到微信收藏同步到GitHub上的？

### ISSUE THREAD

**Issue by Robin-Bi** [izj007/wechat#3]
想把自己微信收藏的文章同步到电脑上来看。

**Comment by izj007** [comment]
如果是直接微信搜藏的，pc端微信就可以直接访问吧。
我这里同步记录是建立了一个微信机器人，获取到我分享的文章就自动分享到github上来

**Comment by Robin-Bi** [comment]
是的，PC端微信可以访问。
我也想向你这样，求问下微信机器人是怎么做的？可以分享给我吗？

**Comment by izj007** [comment]
https://github.com/cixingguangming55555/wechat-bot 我用的是这个

Robin-Bi ***@***.***> 于2022年7月3日周日 14:04写道：
